### ISSUE TITLE
upstream 中写多个fake server 会导致nginx crash

### ISSUE THREAD

**Issue by xukunfeng** [weibocom/nginx-upsync-module#105]
出错配置如下。在upstream中添加两个server会导致 nginx无法正常启动，所有worker process 崩溃。
修改成一个即可以恢复。 
```
upstream test {
        # fake server otherwise ngx_http_upstream will report error when startup
        server 127.0.0.1:11111;
        server 127.0.0.1:11112;

        upsync 127.0.0.1:8081/v1/upstream/myou-data-collect/health/query upsync_timeout=6m upsync_interval=500ms upsync_type=consul strong_dependency=off;
        upsync_dump_path /usr/local/nginx/conf/servers/myou-data-collect.conf;
}
```

nginx 配置
```
configure arguments: --prefix=/usr/local/nginx --sbin-path=/usr/sbin/nginx --conf-path=/usr/local/nginx/nginx.conf --error-log-path=/usr/local/nginx/log/error.log --http-log-path=/usr/local/nginx/log/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --with-cc-opt='-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' --with-pcre=/usr/local/src/pcre-8.34 --with-zlib=/usr/local/src/zlib-1.2.8 --with-openssl=/usr/local/src/openssl-1.0.1g --add-module=/usr/local/src/nginx-upsync-module-master --add-module=/usr/local/src/ngx_cache_purge-2.3
```

异常报错
```
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
*** Error in `nginx: master process /usr/sbin/nginx -c /usr/local/nginx/nginx.conf': malloc(): memory corruption: 0x0000000002595f70 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7e89d)[0x7f2fc498289d]
/lib64/libc.so.6(__libc_malloc+0x4c)[0x7f2fc498426c]
nginx: master process /usr/sbin/nginx -c /usr/local/nginx/nginx.conf(ngx_alloc+0xf)[0x462e8f]
nginx: master process /usr/sbin/nginx -c /usr/local/nginx/nginx.conf(ngx_calloc+0xe)[0x462ede]
nginx: master process /usr/sbin/nginx -c /usr/local/nginx/nginx.conf[0x4d66b8]
nginx: master process /usr/sbin/nginx -c /usr/local/nginx/nginx.conf[0x465cce]
nginx: master process /usr/sbin/nginx -c /usr/local/nginx/nginx.conf[0x46622b]
nginx: master process /usr/sbin/nginx -c /usr/local/nginx/nginx.conf(ngx_spawn_process+0x154)[0x464d64]
nginx: master process /usr/sbin/nginx -c /usr/local/nginx/nginx.conf(ngx_master_process_cycle+0x692)[0x467332]
nginx: master process /usr/sbin/nginx -c /usr/local/nginx/nginx.conf(main+0x7e9)[0x443bf9]
*** Error in `nginx: master process /usr/sbin/nginx -c /usr/local/nginx/nginx.conf': malloc(): memory corruption: 0x0000000002595f70 ***
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f2fc4925b15]
nginx: master process /usr/sbin/nginx -c /usr/local/nginx/nginx.conf[0x443f51]
======= Memory map: ========
00400000-006fc000 r-xp 00000000 fd:01 18819901                           /usr/sbin/nginx
008fb000-008fc000 r--p 002fb000 fd:01 18819901                           /usr/sbin/nginx
008fc000-00924000 rw-p 002fc000 fd:01 18819901                           /usr/sbin/nginx
00924000-00d4d000 rw-p 00000000 00:00 0
02572000-025d2000 rw-p 00000000 00:00 0                                  [heap]
7f2fbc000000-7f2fbc021000 rw-p 00000000 00:00 0
7f2fbc021000-7f2fc0000000 ---p 00000000 00:00 0
7f2fc3cbd000-7f2fc3cd2000 r-xp 00000000 fd:01 67152969                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f2fc3cd2000-7f2fc3ed1000 ---p 00015000 fd:01 67152969                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f2fc3ed1000-7f2fc3ed2000 r--p 00014000 fd:01 67152969                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f2fc3ed2000-7f2fc3ed3000 rw-p 00015000 fd:01 67152969                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f2fc3ed3000-7f2fc44ee000 rw-p 00000000 00:00 0
7f2fc44ee000-7f2fc44fa000 r-xp 00000000 fd:01 67222729                   /usr/lib64/libnss_files-2.17.so
7f2fc44fa000-7f2fc46f9000 ---p 0000c000 fd:01 67222729                   /usr/lib64/libnss_files-2.17.so
7f2fc46f9000-7f2fc46fa000 r--p 0000b000 fd:01 67222729                   /usr/lib64/libnss_files-2.17.so
7f2fc46fa000-7f2fc46fb000 rw-p 0000c000 fd:01 67222729                   /usr/lib64/libnss_files-2.17.so
7f2fc46fb000-7f2fc4701000 rw-p 00000000 00:00 0
7f2fc4701000-7f2fc4703000 r-xp 00000000 fd:01 67154747                   /usr/lib64/libfreebl3.so
7f2fc4703000-7f2fc4902000 ---p 00002000 fd:01 67154747                   /usr/lib64/libfreebl3.so
7f2fc4902000-7f2fc4903000 r--p 00001000 fd:01 67154747                   /usr/lib64/libfreebl3.so
7f2fc4903000-7f2fc4904000 rw-p 00002000 fd:01 67154747                   /usr/lib64/libfreebl3.so
7f2fc4904000-7f2fc4abb000 r-xp 00000000 fd:01 67154744                   /usr/lib64/libc-2.17.so
7f2fc4abb000-7f2fc4cbb000 ---p 001b7000 fd:01 67154744                   /usr/lib64/libc-2.17.so
7f2fc4cbb000-7f2fc4cbf000 r--p 001b7000 fd:01 67154744                   /usr/lib64/libc-2.17.so
7f2fc4cbf000-7f2fc4cc1000 rw-p 001bb000 fd:01 67154744                   /usr/lib64/libc-2.17.so
7f2fc4cc1000-7f2fc4cc6000 rw-p 00000000 00:00 0
7f2fc4cc6000-7f2fc4dc7000 r-xp 00000000 fd:01 67179481                   /usr/lib64/libm-2.17.so
```

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
有意思，貌似自己没有尝试过两个fake server，感觉是个bug，给我点时间check，感谢！

**Comment by xiaokai-wang** [comment]
非常抱歉，不知原因的刷屏了.

**Comment by xiaokai-wang** [comment]
It's a bug, be fixed, please have a try. Thanks.

**Comment by xiaokai-wang** [comment]
It's a bug, be fixed, please have a try. Thanks.

**Comment by insoz** [comment]
修复后的我编译安装后报错如下:

> *** Error in `nginx: worker process': free(): invalid pointer: 0x00007f80c4617d48 ***
2016/09/07 13:43:22 [alert] 18410#0: worker process 18411 exited on signal 6 (core dumped)

core
```nginx
 [New LWP 10602]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nginx: worker process          '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f26d03d8c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f26d03d8c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f26d03dc028 in __GI_abort () at abort.c:89
#2  0x00007f26d04152a4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7f26d05236b0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007f26d042155e in malloc_printerr (ptr=<optimized out>, str=0x7f26d051f801 "free(): invalid pointer", action=1)
    at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00000000004f1c7e in ngx_http_upsync_del_delay_delete (event=<optimized out>)
    at /opt/openresty-patch/nginx-upsync-module/src/ngx_http_upsync_module.c:3116
#6  0x0000000000436552 in ngx_event_expire_timers () at src/event/ngx_event_timer.c:97
#7  0x00000000004361cb in ngx_process_events_and_timers (cycle=cycle@entry=0x7f26d1f043b0) at src/event/ngx_event.c:256
#8  0x000000000043c061 in ngx_worker_process_cycle (cycle=cycle@entry=0x7f26d1f043b0, data=data@entry=0x0)
    at src/os/unix/ngx_process_cycle.c:753
#9  0x000000000043ab34 in ngx_spawn_process (cycle=cycle@entry=0x7f26d1f043b0, proc=0x43bfe0 <ngx_worker_process_cycle>, data=0x0,
    name=0x4fb7cd "worker process", respawn=respawn@entry=0) at src/os/unix/ngx_process.c:198
#10 0x000000000043d102 in ngx_reap_children (cycle=0x7f26d1f043b0) at src/os/unix/ngx_process_cycle.c:621
#11 ngx_master_process_cycle (cycle=cycle@entry=0x7f26d1f043b0) at src/os/unix/ngx_process_cycle.c:174
#12 0x000000000041b2f9 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:367
```

**Comment by xiaokai-wang** [comment]
hi @insoz ,

麻烦再试一下；

**Comment by insoz** [comment]
可以了.

**Comment by xiaokai-wang** [comment]
多谢！
