### ISSUE TITLE
nginx will be blocked while calling getaddrinfo

### ISSUE THREAD

**Issue by bluestn** [weibocom/nginx-upsync-module#134]
如果域名解析比较慢的话，那么在调用getaddrinfo的时候由于执行的是同步操作，导致整个nginx进程卡住。

0  0x00007ffff5d10680 in __poll_nocancel () from /lib64/libc.so.6
#1  0x00007ffff4a97dd4 in __libc_res_nsend () from /lib64/libresolv.so.2
#2  0x00007ffff4a95cce in __libc_res_nquery () from /lib64/libresolv.so.2
#3  0x00007ffff4a968b0 in __libc_res_nsearch () from /lib64/libresolv.so.2
#4  0x00007ffff26c6c53 in _nss_dns_gethostbyname4_r () from /lib64/libnss_dns.so.2
#5  0x00007ffff5d00c08 in gaih_inet () from /lib64/libc.so.6
#6  0x00007ffff5d042cd in getaddrinfo () from /lib64/libc.so.6
#7  0x000000000064441e in ngx_http_upsync_init_server (event=0x7ffff1f8e248) at ../modules/nginx-upsync-module/src/ngx_http_upsync_module.c:3042
#8  0x00000000006430ad in ngx_http_upsync_connect_handler (event=0x7ffff1f8e248) at ../modules/nginx-upsync-module/src/ngx_http_upsync_module.c:2536
#9  0x000000000064307f in ngx_http_upsync_begin_handler (event=0x7ffff1f8e248) at ../modules/nginx-upsync-module/src/ngx_http_upsync_module.c:2519
#10 0x000000000053fcc0 in ngx_event_expire_timers () at src/event/ngx_event_timer.c:94
#11 0x000000000053dd89 in ngx_process_events_and_timers (cycle=0x7ffff3394e10) at src/event/ngx_event.c:256
#12 0x000000000054836a in ngx_single_process_cycle (cycle=0x7ffff3394e10) at src/os/unix/ngx_process_cycle.c:332
#13 0x00000000005126bb in main (argc=1, argv=0x7fffffffe558) at src/core/nginx.c:364

**Comment by xiaokai-wang** [comment]
尝试了？这个函数的功能不会有阻塞吧？

**Comment by bluestn** [comment]
对的，我看到整个进程卡住，过好久域名解析出来了，才有反应。
  if (getaddrinfo((char *) host, NULL, &hints, &res) != 0) {
这个调用应该是同步函数调用。

**Comment by xiaokai-wang** [comment]
卡住一次，之后呢？我的理解这个函数不是每次都远程进行一个DNS 解析调用，而只是进行一个转换？

**Comment by bluestn** [comment]
系统应该有一个缓存，但是如果长时间缓存不太会。

**Comment by xiaokai-wang** [comment]
对，我的理解是，这个函数是去读这个缓存的，进行一个格式的转换 : ).

**Comment by bluestn** [comment]
即便是缓存，也会有缓存过期的时间，会引起block的问题，建议还是能够改成异步调用。谢谢！

**Comment by xiaokai-wang** [comment]
退一步，即使阻塞了，不会对正常的请求有影响，只是配置的更新稍微延迟一下；这个个人觉得暂时还好；
：）

**Comment by bluestn** [comment]
不是的，因为nginx-upsync-module的timer是在work进程里面跑的，nginx是单线程模式的，一旦nginx-upsync-module在timer里面跑起来，block了，会导致其他连接的处理被挂住。不知道我理解的是不是正确。谢谢！

**Comment by xiaokai-wang** [comment]
是的，如果阻塞的话，会影响本work 线程的请求；

你是怎么测试它block 了？gdb 第一次执行？然后我暂时并不认为它会阻塞，或许更多信息？

感谢反馈！

**Comment by bluestn** [comment]
我将nginx搞成非daemon模式，只有一个worker，进行调试，当时正好dns解析好像有点问题，比较慢，结果整个nginx卡死了。既然单个worker有问题，按照您的设计模式，每个worker都会独自跑consul的upstream获取逻辑，自然应该也会在真实环境下面对多worker模式也会产生影响。
关于异步域名解析的代码我已经改好了，不知道怎么提交代码上来。

**Comment by xiaokai-wang** [comment]
有没有尝试着单独测一下getaddrinfo 接口？写个testcase；

欢迎任何patch，按照代码格式提交便可，非常感谢！

**Comment by rouberg** [comment]
能不能不做域名解析, 配置域名时直接把域名设置成server呢, 因为域名可能映射的是动态ip.
@xiaokai-wang

**Comment by haobohuiying** [comment]
* 在以下系统上测试，strace getaddrinfo 函数底层调用poll，使用noblock socket 选项 
```
uname -a
Linux koalii 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux
```
* 在发送和接收的是否分别设置了 5秒超时
* 当/etc/resolv.con 设一个网络不通或者没有dns 服务的ip时，以下测试，getaddrinfo 会阻塞5s
* **不应该在event 时间循环中调用此getaddrinfo**
```
09:55:37 poll([{fd=3, events=POLLIN}], 1, 5000) = 0 (Timeout)
09:55:42 socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 4
```

``` c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <arpa/inet.h>
 
int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "用法: %s <主机名或IP>\n", argv[0]);
        exit(EXIT_FAILURE);
    }
 
    struct addrinfo hints;
    struct addrinfo *result, *rp;
    int ret;
 
    // 初始化 hints 结构 [1]()[2]()
    memset(&hints, 0, sizeof(hints));
    hints.ai_family  = AF_UNSPEC;    // 支持 IPv4/IPv6 
    hints.ai_socktype  = SOCK_STREAM; // 流式套接字 (TCP)
    hints.ai_flags  = AI_CANONNAME;   // 返回规范主机名
 
    // 调用 getaddrinfo [1]()[9]()
    if ((ret = getaddrinfo(argv[1], NULL, &hints, &result)) != 0) {
        fprintf(stderr, "解析错误: %s\n", gai_strerror(ret));
        exit(EXIT_FAILURE);
    }
 
    printf("解析结果: %s\n", argv[1]);
    printf("规范名称: %s\n\n", result->ai_canonname);
 
    // 遍历所有结果 [6]()[7]()
    for (rp = result; rp != NULL; rp = rp->ai_next) {
        char ipstr[INET6_ADDRSTRLEN];
        void *addr;
 
        // 获取 IP 地址指针
        if (rp->ai_family == AF_INET) { // IPv4
            struct sockaddr_in *ipv4 = (struct sockaddr_in *)rp->ai_addr;
            addr = &(ipv4->sin_addr);
        } else { // IPv6 
            struct sockaddr_in6 *ipv6 = (struct sockaddr_in6 *)rp->ai_addr;
            addr = &(ipv6->sin6_addr);
        }
 
        // 转换为可读字符串 [7]()
        inet_ntop(rp->ai_family, addr, ipstr, sizeof(ipstr));
        printf("地址类型: %s\n", 
               (rp->ai_family == AF_INET) ? "IPv4" : "IPv6");
        printf("IP 地址:  %s\n", ipstr);
        printf("套接字类型: %s\n", 
               (rp->ai_socktype == SOCK_STREAM) ? "TCP" : "UDP");
        printf("协议:     %d\n", rp->ai_protocol);
        printf("地址长度: %d\n", (int)rp->ai_addrlen);
        printf("----------------------------\n");
    }
 
    // 释放内存 [1]()
    freeaddrinfo(result);
    return EXIT_SUCCESS;
}
```

```
strace --timestamp ./a.out www.xds1.com
09:55:37 execve("./a.out", ["./a.out", "www.xds1.com"], 0x7ffec32510f0 /* 25 vars */) = 0
09:55:37 brk(NULL)                      = 0x55c802de4000
09:55:37 mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7a4cad6000
09:55:37 access("/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
09:55:37 openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
09:55:37 fstat(3, {st_mode=S_IFREG|0644, st_size=40259, ...}) = 0
09:55:37 mmap(NULL, 40259, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f7a4cacc000
09:55:37 close(3)                       = 0
09:55:37 openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
09:55:37 read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p\236\2\0\0\0\0\0"..., 832) = 832
09:55:37 pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 840, 64) = 840
09:55:37 fstat(3, {st_mode=S_IFREG|0755, st_size=2003408, ...}) = 0
09:55:37 pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 840, 64) = 840
09:55:37 mmap(NULL, 2055800, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f7a4c8d6000
09:55:37 mmap(0x7f7a4c8fe000, 1462272, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x28000) = 0x7f7a4c8fe000
09:55:37 mmap(0x7f7a4ca63000, 352256, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18d000) = 0x7f7a4ca63000
09:55:37 mmap(0x7f7a4cab9000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e2000) = 0x7f7a4cab9000
09:55:37 mmap(0x7f7a4cabf000, 52856, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f7a4cabf000
09:55:37 close(3)                       = 0
09:55:37 mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7a4c8d3000
09:55:37 arch_prctl(ARCH_SET_FS, 0x7f7a4c8d3740) = 0
09:55:37 set_tid_address(0x7f7a4c8d3a10) = 177038
09:55:37 set_robust_list(0x7f7a4c8d3a20, 24) = 0
09:55:37 rseq(0x7f7a4c8d3680, 0x20, 0, 0x53053053) = 0
09:55:37 mprotect(0x7f7a4cab9000, 16384, PROT_READ) = 0
09:55:37 mprotect(0x55c801e17000, 4096, PROT_READ) = 0
09:55:37 mprotect(0x7f7a4cb0c000, 8192, PROT_READ) = 0
09:55:37 prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
09:55:37 munmap(0x7f7a4cacc000, 40259)  = 0
09:55:37 socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
09:55:37 connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
09:55:37 close(3)                       = 0
09:55:37 socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
09:55:37 connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
09:55:37 close(3)                       = 0
09:55:37 getrandom("\xa8\x8e\x88\x3a\xa3\x4b\x99\xe3", 8, GRND_NONBLOCK) = 8
09:55:37 brk(NULL)                      = 0x55c802de4000
09:55:37 brk(0x55c802e05000)            = 0x55c802e05000
09:55:37 newfstatat(AT_FDCWD, "/etc/nsswitch.conf", {st_mode=S_IFREG|0644, st_size=494, ...}, 0) = 0
09:55:37 newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
09:55:37 openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
09:55:37 fstat(3, {st_mode=S_IFREG|0644, st_size=494, ...}) = 0
09:55:37 read(3, "# /etc/nsswitch.conf\n#\n# Example"..., 4096) = 494
09:55:37 read(3, "", 4096)              = 0
09:55:37 fstat(3, {st_mode=S_IFREG|0644, st_size=494, ...}) = 0
09:55:37 close(3)                       = 0
09:55:37 newfstatat(AT_FDCWD, "/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=88, ...}, 0) = 0
09:55:37 openat(AT_FDCWD, "/etc/host.conf", O_RDONLY|O_CLOEXEC) = 3
09:55:37 fstat(3, {st_mode=S_IFREG|0644, st_size=9, ...}) = 0
09:55:37 read(3, "multi on\n", 4096)    = 9
09:55:37 read(3, "", 4096)              = 0
09:55:37 close(3)                       = 0
09:55:37 futex(0x7f7a4cac572c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
09:55:37 openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 3
09:55:37 fstat(3, {st_mode=S_IFREG|0644, st_size=88, ...}) = 0
09:55:37 read(3, "nameserver 10.1.2.243\nnameserver"..., 4096) = 88
09:55:37 read(3, "", 4096)              = 0
09:55:37 uname({sysname="Linux", nodename="koalii", ...}) = 0
09:55:37 fstat(3, {st_mode=S_IFREG|0644, st_size=88, ...}) = 0
09:55:37 close(3)                       = 0
09:55:37 openat(AT_FDCWD, "/etc/hosts", O_RDONLY|O_CLOEXEC) = 3
09:55:37 fstat(3, {st_mode=S_IFREG|0644, st_size=231, ...}) = 0
09:55:37 lseek(3, 0, SEEK_SET)          = 0
09:55:37 read(3, "127.0.0.1\tlocalhost\n127.0.1.1\tko"..., 4096) = 231
09:55:37 read(3, "", 4096)              = 0
09:55:37 close(3)                       = 0
09:55:37 socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 3
09:55:37 setsockopt(3, SOL_IP, IP_RECVERR, [1], 4) = 0
09:55:37 connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.1.2.243")}, 16) = 0
09:55:37 poll([{fd=3, events=POLLOUT}], 1, 0) = 1 ([{fd=3, revents=POLLOUT}])
09:55:37 sendmmsg(3, [{msg_hdr={msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\2779\1\0\0\1\0\0\0\0\0\0\3www\4xds1\3com\0\0\1\0\1", iov_len=30}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, msg_len=30}, {msg_hdr={msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\261!\1\0\0\1\0\0\0\0\0\0\3www\4xds1\3com\0\0\34\0\1", iov_len=30}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, msg_len=30}], 2, MSG_NOSIGNAL) = 2
09:55:37 poll([{fd=3, events=POLLIN}], 1, 5000) = 0 (Timeout)
09:55:42 socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 4
09:55:42 setsockopt(4, SOL_IP, IP_RECVERR, [1], 4) = 0
09:55:42 connect(4, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.0.1.9")}, 16) = 0
09:55:42 poll([{fd=4, events=POLLOUT}], 1, 0) = 1 ([{fd=4, revents=POLLOUT}])
09:55:42 sendmmsg(4, [{msg_hdr={msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\2779\1\0\0\1\0\0\0\0\0\0\3www\4xds1\3com\0\0\1\0\1", iov_len=30}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, msg_len=30}, {msg_hdr={msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\261!\1\0\0\1\0\0\0\0\0\0\3www\4xds1\3com\0\0\34\0\1", iov_len=30}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, msg_len=30}], 2, MSG_NOSIGNAL) = 2
09:55:42 poll([{fd=4, events=POLLIN}], 1, 3000) = 1 ([{fd=4, revents=POLLIN}])
09:55:43 ioctl(4, FIONREAD, [103])      = 0
09:55:43 recvfrom(4, "\2779\201\203\0\1\0\0\0\1\0\0\3www\4xds1\3com\0\0\1\0\1\300\25"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.0.1.9")}, [28 => 16]) = 103
09:55:43 poll([{fd=4, events=POLLIN}], 1, 2971) = 1 ([{fd=4, revents=POLLIN}])
09:55:43 ioctl(4, FIONREAD, [103])      = 0
09:55:43 recvfrom(4, "\261!\201\203\0\1\0\0\0\1\0\0\3www\4xds1\3com\0\0\34\0\1\300\25"..., 65536, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.0.1.9")}, [28 => 16]) = 103
09:55:43 close(3)                       = 0
09:55:43 close(4)                       = 0
09:55:43 write(2, "\350\247\243\346\236\220\351\224\231\350\257\257: Name or service no"..., 40解析错误: Name or service not known
) = 40
09:55:43 exit_group(1)                  = ?
09:55:43 +++ exited with 1 +++

```

## 一些文章确实说getaddrinfo 会阻塞；
https://lists.busybox.net/pipermail/busybox/2012-July/078123.html
